name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # You can adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag guresonur/devtron-dashboard-19102023:0.0.1 .

      - name: Log in to Docker Hub (or another registry)
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push guresonur/devtron-dashboard-19102023:0.0.1
